2025-06-03 11:59:25,230 ERROR scheduler Exception in Enqueue Events for Site nexchar2.local
Traceback (most recent call last):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 108, in get_connection
    conn = self._get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 114, in _get_connection
    return self.create_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 117, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_a3ff15671ac7bbb4'@'localhost' (using password: YES)")
2025-06-03 12:00:25,250 ERROR scheduler Exception in Enqueue Events for Site nexchar2.local
Traceback (most recent call last):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 108, in get_connection
    conn = self._get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 114, in _get_connection
    return self.create_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 117, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_a3ff15671ac7bbb4'@'localhost' (using password: YES)")
2025-06-03 12:01:25,411 ERROR scheduler Exception in Enqueue Events for Site nexchar2.local
Traceback (most recent call last):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 108, in get_connection
    conn = self._get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 114, in _get_connection
    return self.create_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 117, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_a3ff15671ac7bbb4'@'localhost' (using password: YES)")
2025-06-03 12:02:25,506 ERROR scheduler Exception in Enqueue Events for Site nexchar2.local
Traceback (most recent call last):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 108, in get_connection
    conn = self._get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 114, in _get_connection
    return self.create_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 117, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_a3ff15671ac7bbb4'@'localhost' (using password: YES)")
2025-06-03 12:04:08,879 ERROR scheduler Exception in Enqueue Events for Site nexchar2.local
Traceback (most recent call last):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 108, in get_connection
    conn = self._get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 114, in _get_connection
    return self.create_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 117, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_a3ff15671ac7bbb4'@'localhost' (using password: YES)")
2025-06-03 12:05:08,907 ERROR scheduler Exception in Enqueue Events for Site nexchar2.local
Traceback (most recent call last):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 108, in get_connection
    conn = self._get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 114, in _get_connection
    return self.create_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 117, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_a3ff15671ac7bbb4'@'localhost' (using password: YES)")
2025-06-03 12:06:09,176 ERROR scheduler Exception in Enqueue Events for Site nexchar2.local
Traceback (most recent call last):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 108, in get_connection
    conn = self._get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 114, in _get_connection
    return self.create_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 117, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_a3ff15671ac7bbb4'@'localhost' (using password: YES)")
2025-06-03 12:07:36,623 ERROR scheduler Exception in Enqueue Events for Site nexchar2.local
Traceback (most recent call last):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 108, in get_connection
    conn = self._get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 114, in _get_connection
    return self.create_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 117, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_a3ff15671ac7bbb4'@'localhost' (using password: YES)")
2025-06-03 12:08:36,893 ERROR scheduler Exception in Enqueue Events for Site nexchar2.local
Traceback (most recent call last):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 108, in get_connection
    conn = self._get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 114, in _get_connection
    return self.create_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 117, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_a3ff15671ac7bbb4'@'localhost' (using password: YES)")
2025-06-03 12:09:36,914 ERROR scheduler Exception in Enqueue Events for Site nexchar2.local
Traceback (most recent call last):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 108, in get_connection
    conn = self._get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 114, in _get_connection
    return self.create_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 117, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_a3ff15671ac7bbb4'@'localhost' (using password: YES)")
2025-06-03 12:10:37,021 ERROR scheduler Exception in Enqueue Events for Site nexchar2.local
Traceback (most recent call last):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 108, in get_connection
    conn = self._get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 114, in _get_connection
    return self.create_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 117, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_a3ff15671ac7bbb4'@'localhost' (using password: YES)")
2025-06-03 12:11:37,116 ERROR scheduler Exception in Enqueue Events for Site nexchar2.local
Traceback (most recent call last):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 108, in get_connection
    conn = self._get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 114, in _get_connection
    return self.create_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 117, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_a3ff15671ac7bbb4'@'localhost' (using password: YES)")
2025-06-03 13:26:55,446 ERROR scheduler Exception in Enqueue Events for Site nexchar.local
Traceback (most recent call last):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 108, in get_connection
    conn = self._get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 114, in _get_connection
    return self.create_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 117, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_6c8a96326ab68a59'@'localhost' (using password: YES)")
2025-06-03 13:27:55,469 ERROR scheduler Exception in Enqueue Events for Site nexchar.local
Traceback (most recent call last):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 108, in get_connection
    conn = self._get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 114, in _get_connection
    return self.create_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 117, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_6c8a96326ab68a59'@'localhost' (using password: YES)")
2025-06-03 13:28:55,565 ERROR scheduler Exception in Enqueue Events for Site nexchar.local
Traceback (most recent call last):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 99, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 143, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/utils/scheduler.py", line 156, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 837, in get_single_value
    ).run()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 207, in sql
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/database.py", line 112, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 108, in get_connection
    conn = self._get_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 114, in _get_connection
    return self.create_connection()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/apps/frappe/frappe/database/mariadb/database.py", line 117, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/shobhit/Nexchar-bench/nexchar-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_6c8a96326ab68a59'@'localhost' (using password: YES)")
